connection:
  ip: 0.0.0.0
  port: 7171
  version_min: 100
  version_str: "1.0.0"

database:
  ip: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: ruby
  requireSSL: true

encryption:
  salt: ruby

motd:
  number: 0
  message: Bem-vindo!

worlds:
  - id: 0
    ip: 0.0.0.0
    name: Ruby
    port: 7172
  - id: 1
    name: Crystal
    ip: 0.0.0.0
    port: 7173
